# Generated by Django 5.1.2 on 2024-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
